{% set name = "libmicrohttpd" %}
{% set version = "0.9.72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-{{ version }}.tar.gz
  sha256: 0ae825f8e0d7f41201fd44a0df1cf454c1cb0bc50fe9d59c26552260264c2ff8

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libmicrohttpd", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - gnutls

test:
  commands:
    - test -f $PREFIX/lib/libmicrohttpd${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/microhttpd.h  # [unix]

about:
  home: https://www.gnu.org/software/libmicrohttpd/
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Light HTTP/1.1 server library

extra:
  recipe-maintainers:
    - xhochy
