{% set name = "libmicrohttpd" %}
{% set version = "0.9.76" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-{{ version }}.tar.gz
  sha256: f0b1547b5a42a6c0f724e8e1c1cb5ce9c4c35fb495e7d780b9930d35011ceb4c

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libmicrohttpd", max_pin="x.x") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - gnutls 3.6.15

test:
  commands:
    - test -f $PREFIX/lib/libmicrohttpd${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/microhttpd.h  # [unix]

about:
  home: https://www.gnu.org/software/libmicrohttpd/
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Light HTTP/1.1 server library
  description: |
    GNU libmicrohttpd is a GNU package offering a C library that provides
    a compact API and implementation of an HTTP 1.1 web server (HTTP 1.0
    is also supported).  GNU libmicrohttpd only implements the HTTP 1.1
    protocol.  The main application must still provide the application
    logic to generate the content.
  doc_url: https://www.gnu.org/software/libmicrohttpd/
  # There is an unoffficial mirror on GitHub as well:
  # https://github.com/Karlson2k/libmicrohttpd/tree/master
  dev_url: https://git.gnunet.org/libmicrohttpd.git

extra:
  skip-lints:
    # There are no Python tests for this project. All tests are executed as
    # shell scripts.
    - missing_tests
  recipe-maintainers:
    - xhochy
